#print("hello world")
#name=input("enter your name")
#print("hello" ,name)
#number=input("enter number")
#print("your num",number)
variables=input("enter variables")
print("your variables",variables)